version: '3'

services:
  nodejsorder:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejsorder
    container_name: nodejsorder
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:$PORT"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - app-network
    command: npm run start
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:  