version: '3'

services:
  nodejsorder:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejsorder
    container_name: nodejsorder
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:$PORT"
    volumes:
      - .:/usr/src/app
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules
    networks:
      - app-network
    command: npm run start
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27018:27017"
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:  